# Generated by Django 4.2.22 on 2025-06-27 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ministrantes',
            field=models.ManyToManyField(help_text='Para selecionar mais de um ministrante, pressione CTRL e selecione com o mouse', related_name='ministrantes', to=settings.AUTH_USER_MODEL, verbose_name='Ministrante(s)'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, help_text='Coloque aqui uma descrição do evento para ajudar os autores a submeterem seus trabalhos', max_length=500, null=True, verbose_name='Descrição do evento'),
        ),
    ]
