# Generated by Django 4.2.22 on 2025-06-27 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_evento_ministrantes_alter_evento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='carga_horaria',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Carga horária do evento '),
        ),
    ]
