# Generated by Django 4.2.22 on 2025-07-09 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evento', '0005_alter_evento_ministrantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='ministrantes',
            field=models.ManyToManyField(blank=True, help_text='Para selecionar mais de um ministrante, pressione CTRL e selecione com o mouse', null=True, related_name='ministrantes', to=settings.AUTH_USER_MODEL, verbose_name='Ministrante(s)'),
        ),
    ]
