# Generated by Django 4.2.22 on 2025-07-10 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_alter_evento_ministrantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='carga_horaria',
            field=models.DecimalField(decimal_places=0, default=1, help_text='* Campo obrigatório. Use apenas números inteiros, sem ponto ou vírgula. Carga máxima de 20 horas.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Carga horária do evento '),
        ),
    ]
