# Generated by Django 4.2.22 on 2025-09-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_alter_evento_carga_horaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='frequencia_liberada',
            field=models.BooleanField(default=True, help_text='Se liberada, o evento permite que os participantes solicitem a frequência desde que o horário do registro esteja dentro da carga horária do evento.', verbose_name='Libera a frequência'),
        ),
    ]
