# Generated by Django 4.2.22 on 2025-10-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='destinatario',
            field=models.CharField(choices=[('TODOS', 'Todos'), ('CLIENTE', 'Cliente')], default='TODOS', max_length=20, verbose_name='Destinatários *'),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se ativo, o aviso aparece na home dos clientes', verbose_name='Selecione para publicar na home dos usuários o aviso'),
        ),
    ]
