# Generated by Django 4.2.22 on 2025-10-08 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadoClinico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolus_alimentar', models.PositiveIntegerField(blank=True, help_text='Unidades de insulina para cada 10g de carboidrato, por exemplo', null=True, verbose_name='Bolus Alimentar (U)')),
                ('bolus_correcao', models.PositiveIntegerField(blank=True, help_text='Unidades de insulina para cada 10mg/dL acima da meta, por exemplo', null=True, verbose_name='Bolus Correção (U)')),
                ('altura', models.PositiveIntegerField(blank=True, null=True, verbose_name='Altura (cm)')),
                ('peso', models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso (kg)')),
                ('data_registro', models.DateField(auto_now=True, verbose_name='Data do registro')),
                ('is_active', models.BooleanField(default=False, help_text='Se ativo, o dado pode ser utilizado no sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('cliente', models.ForeignKey(help_text='* Campos obrigatórios', on_delete=django.db.models.deletion.PROTECT, related_name='dados_clinicos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente *')),
                ('medicamentos', models.ManyToManyField(blank=True, null=True, related_name='medicamentos', to='medicamento.medicamento', verbose_name='Medicamentos')),
            ],
            options={
                'verbose_name': 'dado clínico',
                'verbose_name_plural': 'dados clínicos',
                'ordering': ['cliente'],
            },
        ),
    ]
