# Generated by Django 4.2.22 on 2025-10-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dado_clinico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadoclinico',
            options={'ordering': ['cliente', '-data_registro'], 'verbose_name': 'dado clínico', 'verbose_name_plural': 'dados clínicos'},
        ),
    ]
