# Generated by Django 4.2.22 on 2025-10-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dado_clinico', '0002_alter_dadoclinico_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoclinico',
            name='glicemia_meta',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Glicemia Meta (mg/dL)'),
        ),
    ]
