# Generated by Django 4.2.22 on 2025-10-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dado_clinico', '0003_dadoclinico_glicemia_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoclinico',
            name='tipo_diabetes',
            field=models.CharField(blank=True, choices=[('SEM DIABETES', 'Sem Diabetes'), ('PRE-DIABETES', 'Pré-Diabetes'), ('DIABETES GESTACIONAL', 'Diabetes Gestacional'), ('DIABETES TIPO 2', 'Diabetes Tipo 2'), ('DIABETES TIPO 1', 'Diabetes Tipo 1')], max_length=20, null=True, verbose_name='Tipo de Diabetes'),
        ),
    ]
