# Generated by Django 4.2.22 on 2025-11-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dado_clinico', '0004_dadoclinico_tipo_diabetes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoclinico',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se ativo, o dado pode ser utilizado no sistema', verbose_name='Ativo'),
        ),
    ]
