# Generated by Django 4.2.22 on 2025-09-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comercial', models.CharField(help_text='ex: Novorapid, Lantus, Metformina', max_length=25, verbose_name='Nome comercial *')),
                ('principio_ativo', models.CharField(choices=[('INSULINA ASPARTE', 'Insulina asparte'), ('INSULINA GLARGINA', 'Insulina glargina'), ('METFORMINA', 'Metformina')], max_length=18, verbose_name='Princípio ativo *')),
                ('classe_terapeutica', models.CharField(choices=[('INSULINA RAPIDA', 'Insulina de ação rápida'), ('INSULINA BASAL', 'Insulina basal'), ('ORAL', 'Antidiabético oral')], max_length=25, verbose_name='Classe terapêutica *')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'medicamento',
                'verbose_name_plural': 'medicamentos',
                'ordering': ['nome_comercial'],
                'unique_together': {('nome_comercial', 'principio_ativo', 'classe_terapeutica')},
            },
        ),
    ]
