# Generated by Django 4.2.22 on 2025-10-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se ativo, o medicamento fica disponível para seleção no sistema', verbose_name='Selecione para usar medicamento no sistema'),
        ),
    ]
