# Generated by Django 4.2.22 on 2025-08-24 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Titulo *')),
                ('descricao', models.TextField(verbose_name='Detalhamento do relatório *')),
                ('script_sql', models.TextField(blank=True, null=True, verbose_name='Script SQL')),
                ('resposta', models.TextField(blank=True, null=True, verbose_name='Respostas do relatório')),
                ('data', models.DateField(default=datetime.datetime.now, verbose_name='Data de geração do relatório *')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'relatório',
                'verbose_name_plural': 'relatórios',
                'ordering': ['-data', 'titulo'],
            },
        ),
    ]
