# Generated by Django 4.2.22 on 2025-06-11 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_frequencia', models.DateTimeField(auto_now_add=True)),
                ('codigo_frequencia', models.CharField(blank=True, help_text='Use o código de frequência informado pela organização do evento.', max_length=20, null=True, verbose_name='Código de frequência')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inscricao', to='inscricao.inscricao', verbose_name='Inscrição do evento *')),
            ],
            options={
                'verbose_name': 'frequência',
                'verbose_name_plural': 'frequências',
                'ordering': ['inscricao__participante__nome'],
                'unique_together': {('inscricao', 'codigo_frequencia')},
            },
        ),
    ]
