# Generated by Django 4.2.22 on 2025-06-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='codigo_frequencia',
            field=models.CharField(blank=True, help_text='Use o código de frequência informado pela organização do evento.', max_length=30, null=True, verbose_name='Código de frequência'),
        ),
    ]
