# Generated by Django 4.2.22 on 2025-10-03 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Use dd/mm/aaaa', verbose_name='Data da atividade física *')),
                ('hora', models.TimeField(help_text='Use hh:mm', verbose_name='Hora da atividade física *')),
                ('duracao', models.PositiveIntegerField(verbose_name='Quantos minutos em atividade *')),
                ('esforco', models.CharField(choices=[('6 - MUITO FÁCIL', '6 - Muito fácil'), ('9 - FÁCIL', '9 - Fácil'), ('11 - RELATIVAMENTE FÁCIL', '11 - Relativamente fácil'), ('13 - LIGEIRAMENTE CANSATIVO', '13 - Ligeiramente cansativo'), ('15 - CANSATIVO', '15 - Cansativo'), ('17 - MUITO CANSATIVO', '17 - Muito cansativo'), ('19 - EXAUSTIVO', '19 - Exaustivo')], help_text='Em relação ao esforço na atividade', max_length=27, verbose_name='Esforço subjetivo *')),
                ('frequencia_cardiaca_media', models.PositiveIntegerField(blank=True, help_text='Caso tenha utilizado um frequêncímetro durante a atividade', null=True, verbose_name='Frequência cardíaca média durante a atividade')),
                ('total_calorias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de calorias queimadas durante a atividade')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercicio.exercicio', verbose_name='Atividade física realizada')),
                ('cliente', models.ForeignKey(help_text='* indica campo obrigatório.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario *')),
            ],
            options={
                'verbose_name': 'registro atividade',
                'verbose_name_plural': 'registros atividades',
                'ordering': ['data', 'hora', 'atividade'],
            },
        ),
    ]
