# Generated by Django 4.2.22 on 2025-10-03 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro_atividade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroatividade',
            name='cliente',
            field=models.ForeignKey(help_text='* indica campo obrigatório.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cliente ou paciente *'),
        ),
    ]
