# Generated by Django 4.2.22 on 2025-10-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_atividade', '0002_alter_registroatividade_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroatividade',
            options={'ordering': ['data', 'hora', 'cliente__nome', 'atividade'], 'verbose_name': 'registro atividade', 'verbose_name_plural': 'registros atividades'},
        ),
    ]
