# Generated by Django 4.2.22 on 2025-07-07 14:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtestadoManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, help_text='* Campo obrigatório', max_length=150, verbose_name='Nome do atestado_manual *')),
                ('atividade', models.TextField(blank=True, help_text='Coloque aqui uma descrição do atestado_manual para ajudar os autores a submeterem seus trabalhos', max_length=500, null=True, verbose_name='Descrição do atestado_manual')),
                ('instituicao', models.CharField(help_text='* Campo obrigatório', max_length=150, null=True, verbose_name='Departamento ou Setor ou Grupo responsável pelo evento *')),
                ('data_inicio', models.DateField(help_text='Use dd/mm/aaaa', max_length=10, null=True, verbose_name='Data do evento *')),
                ('data_fim', models.DateField(help_text='Use dd/mm/aaaa', max_length=10, null=True, verbose_name='Data limite de inscrição ao evento *')),
                ('carga_horaria', models.DecimalField(decimal_places=0, default=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Carga horária do evento ')),
                ('codigo_matricula', models.CharField(max_length=20, verbose_name='Código matrícula gerado por hash *')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, o evento está liberado para chamada de artigos', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atestado_admin', to=settings.AUTH_USER_MODEL, verbose_name='Coordenador responsável *')),
            ],
            options={
                'verbose_name': 'atestado',
                'verbose_name_plural': 'atestados',
                'ordering': ['-is_active', 'nome', 'data_inicio'],
                'unique_together': {('nome', 'data_inicio')},
            },
        ),
    ]
