# Generated by Django 4.2.22 on 2025-07-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atestado_manual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atestadomanual',
            name='responsavel',
            field=models.CharField(help_text='* Campo obrigatório', max_length=150, verbose_name='Coordenador responsável *'),
        ),
    ]
