# Generated by Django 4.2.22 on 2025-07-10 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atestado_manual', '0004_alter_atestadomanual_carga_horaria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atestadomanual',
            options={'ordering': ['-is_active', 'pessoa', 'data_inicio'], 'verbose_name': 'atestado', 'verbose_name_plural': 'atestados'},
        ),
        migrations.AlterUniqueTogether(
            name='atestadomanual',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='atestadomanual',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoa', to=settings.AUTH_USER_MODEL, verbose_name='Nome do pessoa *'),
        ),
        migrations.AlterUniqueTogether(
            name='atestadomanual',
            unique_together={('pessoa', 'codigo_matricula')},
        ),
        migrations.RemoveField(
            model_name='atestadomanual',
            name='nome',
        ),
    ]
