# Generated by Django 4.2.22 on 2025-07-10 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atestado_manual', '0005_alter_atestadomanual_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atestadomanual',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoa', to=settings.AUTH_USER_MODEL, verbose_name='Nome *'),
        ),
    ]
