# Generated by Django 4.2.22 on 2025-07-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atestado_manual', '0006_alter_atestadomanual_pessoa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atestadomanual',
            options={'ordering': ['-is_active', 'pessoa', '-data_inicio'], 'verbose_name': 'atestado', 'verbose_name_plural': 'atestados'},
        ),
    ]
