# Generated by Django 4.2.22 on 2025-06-11 21:21

import django.contrib.auth.models
from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tipo', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('COORDENADOR', 'Coordenador de Evento'), ('PARTICIPANTE', 'Participante')], default='MEMBRO', help_text='* Campos obrigatórios', max_length=15, verbose_name='Tipo do usuário *')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo *')),
                ('instituicao', models.CharField(help_text='Registre a instituição, ou universidade, ou empresa', max_length=50, verbose_name='Instituição a que pertence *')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Email')),
                ('celular', models.CharField(help_text='Use DDD, por exemplo 55987619832', max_length=14, verbose_name='Número celular com DDD *')),
                ('cpf', models.CharField(help_text='ATENÇÃO: Somente os NÚMEROS', max_length=14, verbose_name='CPF *')),
                ('aceita_termo', models.BooleanField(default=False, help_text='Se marcado, usuário tem consentimento de uso do sistema', verbose_name='Marque o aceite do termo de consentimento')),
                ('eh_avaliador', models.BooleanField(default=False, help_text='Se ativo, o usuário tem permissão para acessar o sistema', verbose_name='É avaliador')),
                ('is_active', models.BooleanField(default=False, help_text='Se ativo, o usuário tem permissão para acessar o sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['-is_active', '-tipo', 'nome'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('administradores', usuario.models.AdministradorAtivoManager()),
                ('coordenadores', usuario.models.CoordenadorAtivoManager()),
                ('participantes', usuario.models.ParticipanteAtivoManager()),
                ('ministrantes', usuario.models.MinistranteAtivoManager()),
                ('usuarios_ativos', usuario.models.UsuarioAtivoManager()),
            ],
        ),
    ]
