# Generated by Django 4.2.22 on 2025-06-27 10:42

import django.contrib.auth.models
from django.db import migrations
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('administradores', usuario.models.AdministradorAtivoManager()),
                ('coordenadores', usuario.models.CoordenadorAtivoManager()),
                ('participantes', usuario.models.ParticipanteAtivoManager()),
                ('lista_ministrantes', usuario.models.MinistranteAtivoManager()),
                ('usuarios_ativos', usuario.models.UsuarioAtivoManager()),
            ],
        ),
    ]
