# Generated by Django 4.2.22 on 2025-07-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-is_active', 'nome'], 'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
    ]
