# Generated by Django 4.2.22 on 2025-10-09 14:33

import django.contrib.auth.models
from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('administradores', usuario.models.AdministradorAtivoManager()),
                ('clientes', usuario.models.ClienteAtivoManager()),
                ('nutricionistas', usuario.models.NutricionistaAtivoManager()),
                ('medicos', usuario.models.MedicoAtivoManager()),
                ('educadores_fisicos', usuario.models.EducadorFisicoAtivoManager()),
                ('usuarios_ativos', usuario.models.UsuarioAtivoManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='eh_avaliador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='instituicao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, help_text='Informe sua data de nascimento (dd/mm/aaaa)', null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], help_text='Campo obrigatório para cálculo de gasto energético/calórico e consumo alimentar', max_length=10, null=True, verbose_name='Sexo *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('CLIENTE', 'Cliente'), ('MEDICO', 'Médico'), ('NUTRICIONISTA', 'Nutricionista'), ('EDUCADOR FISICO', 'Educador Físico'), ('OUTRO PROFISSIONAL DE SAUDE', 'Outro Profissional de Saúde')], default='CLIENTE', help_text='* Campos obrigatórios', max_length=30, verbose_name='Tipo do usuário *'),
        ),
    ]
