# Generated by Django 4.2.22 on 2025-10-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_usuario_managers_remove_usuario_eh_avaliador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('FEMININO', 'Feminino'), ('MASCULINO', 'Masculino')], help_text='Campo obrigatório para cálculo de gasto energético/calórico e consumo alimentar', max_length=10, null=True, verbose_name='Sexo *'),
        ),
    ]
