# Generated by Django 4.2.22 on 2025-10-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimento', '0001_initial'),
        ('dado_clinico', '0002_alter_dadoclinico_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRefeicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_alimentacao', models.TextField(help_text='Descreva o que foi consumido na refeição.', max_length=1000, verbose_name='Registro alimentar *')),
                ('glicemia_vigente', models.PositiveIntegerField(blank=True, help_text='Valor da glicemia antes da refeição, se disponível', null=True, verbose_name='Glicemia vigente (mg/dL)')),
                ('quantidade_insulina_recomendada', models.PositiveIntegerField(blank=True, help_text='Unidades de insulina recomendada para a refeição, se aplicável', null=True, verbose_name='Quantidade de insulina recomendada (U)')),
                ('total_carboidratos', models.PositiveIntegerField(blank=True, help_text='Total de carboidratos consumidos na refeição, se conhecido', null=True, verbose_name='Total de carboidratos (g)')),
                ('total_calorias', models.PositiveIntegerField(blank=True, help_text='Total de calorias consumidas na refeição, se conhecido', null=True, verbose_name='Total de calorias (kcal)')),
                ('data_hora_registro', models.DateTimeField(auto_now=True, verbose_name='Data e hora do registro')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('alimentos', models.ManyToManyField(blank=True, help_text='* indica campo obrigatório.', null=True, to='alimento.alimento', verbose_name='Alimentos consumidos *')),
                ('cliente', models.ForeignKey(help_text='* indica campo obrigatório.', on_delete=django.db.models.deletion.PROTECT, to='dado_clinico.dadoclinico', verbose_name='Cliente ou paciente *')),
            ],
            options={
                'verbose_name': 'registro refeição',
                'verbose_name_plural': 'registros refeições',
                'ordering': ['cliente__cliente__nome', '-data_hora_registro'],
            },
        ),
    ]
