# Generated by Django 4.2.22 on 2025-10-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_refeicao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrorefeicao',
            name='nome_insulina',
            field=models.CharField(blank=True, help_text='Nome da insulina recomendada para a refeição, se aplicável', max_length=200, null=True, verbose_name='Nome da insulina recomendada'),
        ),
    ]
