# Generated by Django 4.2.22 on 2025-11-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_refeicao', '0002_registrorefeicao_nome_insulina'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrorefeicao',
            name='quantidade_tokens_consumidos',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de tokens utilizados *'),
        ),
    ]
