# Generated by Django 4.2.22 on 2025-11-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_refeicao', '0003_registrorefeicao_quantidade_tokens_consumidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrorefeicao',
            name='quantidade_tokens_consumidos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de tokens utilizados *'),
        ),
    ]
